"""Capture current database state after manual stamp

Revision ID: 4373bef20db5
Revises: da2162410d65
Create Date: 2025-11-21 14:30:52.205884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4373bef20db5'
down_revision: Union[str, None] = 'da2162410d65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('CartItem', 'subtotal',
               existing_type=sa.DECIMAL(precision=29, scale=2),
               type_=sa.DECIMAL(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('CartItem', 'source',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("('inventory')"))
    op.drop_constraint(op.f('FK__vw_Medica__store__36339604'), 'vw_MedicalStoreDashboard', type_='foreignkey')
    op.create_foreign_key(None, 'vw_MedicalStoreDashboard', 'MedicalStore', ['store_id'], ['store_id'], source_schema='dbo', ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vw_MedicalStoreDashboard', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__vw_Medica__store__36339604'), 'vw_MedicalStoreDashboard', 'MedicalStore', ['store_id'], ['store_id'])
    op.alter_column('CartItem', 'source',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("('inventory')"))
    op.alter_column('CartItem', 'subtotal',
               existing_type=sa.DECIMAL(precision=18, scale=2),
               type_=sa.DECIMAL(precision=29, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
