from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Computed
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision: str = 'baeb1bcde0b0'
down_revision: Union[str, None] = '4373bef20db5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # FIX for (pyodbc.ProgrammingError): Cannot alter column 'subtotal' because it is 'COMPUTED'.
    # We must DROP the computed column first, and then ADD the new, non-computed column.
    
    # 1. Drop the existing computed column (DECIMAL 29, 2)
    op.drop_column('CartItem', 'subtotal')
    
    # 2. Add the column back as a standard DECIMAL (18, 2) column
    op.add_column('CartItem', sa.Column('subtotal', sa.DECIMAL(precision=18, scale=2), nullable=True))
    
    # Continue with the other original commands:
    op.alter_column('CartItem', 'source',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("('inventory')"))
    op.drop_constraint(op.f('FK__vw_Medica__store__36339604'), 'vw_MedicalStoreDashboard', type_='foreignkey')
    op.create_foreign_key(None, 'vw_MedicalStoreDashboard', 'MedicalStore', ['store_id'], ['store_id'], source_schema='dbo', ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vw_MedicalStoreDashboard', schema='dbo', type_='foreignkey')
    op.create_foreign_key(op.f('FK__vw_Medica__store__36339604'), 'vw_MedicalStoreDashboard', 'MedicalStore', ['store_id'], ['store_id'])
    op.alter_column('CartItem', 'source',
               existing_type=sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("('inventory')"))

    # Reverting the drop/add for 'subtotal':
    # 1. Drop the standard column
    op.drop_column('CartItem', 'subtotal')

    # 2. Re-add the original computed column (DECIMAL 29, 2).
    # NOTE: You MUST replace 'YOUR_COMPUTATION_EXPRESSION_HERE' with the EXACT SQL formula
    # that originally defined 'subtotal' as a computed column in the database.
    # E.g., sa.Computed(text('quantity * price'))
    op.add_column('CartItem', 
                  sa.Column('subtotal', sa.DECIMAL(precision=29, scale=2), 
                            Computed(text('YOUR_COMPUTATION_EXPRESSION_HERE'))))
    
    # ### end Alembic commands ###
